export const BACK_HOST = process.env.REACT_APP_BACK_HOST;
export const BASE_URL = process.env.REACT_APP_BASE_URL;
export const API_URL = process.env.REACT_APP_API_URL;
export const PUP_URL = process.env.REACT_APP_PUP_URL;

//account
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';
export const ACCOUNT_ADD = 'ACCOUNT_ADD';
export const ACCOUNT_EDIT = 'ACCOUNT_EDIT';
export const ACCOUNTS_LOADER = 'ACCOUNT_EDIT';
export const LOAD_ALL_ACCOUNTS = 'LOAD_ALL_ACCOUNTS';

export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

//mailing
export const LOAD_ALL_MAILING_ITEMS = 'LOAD_ALL_MAILING_ITEMS';
export const DELETE_MAILING_ITEM = 'DELETE_MAILING_ITEM';
export const MAILING_LOADER = 'MAILING_LOADER';

//variables
export const LOAD_ALL_VARIABLES = 'LOAD_ALL_VARIABLES';
export const VARIABLES_LOADER = 'VARIABLES_LOADER';
export const VARIABLE_DELETE = 'VARIABLE_DELETE';
export const VARIABLE_ADD = 'VARIABLE_ADD';
export const VARIABLE_EDIT = 'VARIABLE_EDIT';

//add mailing page
export const MAILING_CONFIGURATION_OPTIONS = 'MAILING_CONFIGURATION_OPTIONS';
export const MAILING_CONFIGURATION_OPTIONS_LOADER = 'MAILING_CONFIGURATION_OPTIONS_LOADER';
export const GET_NEW_SERVICE_ARR = 'GET_NEW_SERVICE_ARR';
export const ADD_NEW_CONDITION = 'ADD_NEW_CONDITION';
export const REMOVE_CONDITION = 'REMOVE_CONDITION';
export const REMOVE_BINDING = 'REMOVE_BINDING';
export const ADD_NEW_BINDING = 'ADD_NEW_BINDING';